In [12]:
import pandas as pd
import numpy as np 
import matplotlib as plt
from pathlib import Path

BASE_DIR = Path.cwd()
DATA_PATH = BASE_DIR.parent / "Data" / "healthcare_dataset_processed.csv"

df = pd.read_csv(DATA_PATH)

df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   First Name          55500 non-null  str
 1   Last Name           55500 non-null  str
 2   Age                 55500 non-null  int64
 3   Gender              55500 non-null  str
 4   Blood Type          55500 non-null  str
 5   Medical Condition   55500 non-null  str
 6   Date of Admission   55500 non-null  str
 7   Doctor              55500 non-null  str
 8   Hospital            55500 non-null  str
 9   Insurance Provider  55500 non-null  str
 10  Billing Amount      55500 non-null  float64
 11  Admission Type      55500 non-null  str
 12  Discharge Date      55500 non-null  str
 13  Medication          55500 non-null  str
 14  Age Range           55500 non-null  str
dtypes: float64(1), int64(1), str(13)
memory usage: 6.4 MB

,First Name,Last Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Admission Type,Discharge Date,Medication,Age Range
0,Bobby,Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.28,Urgent,2024-02-02,Paracetamol,21-30
1,Leslie,Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.33,Emergency,2019-08-26,Ibuprofen,61-70
2,Danny,Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.10,Emergency,2022-10-07,Aspirin,71-80
3,Andrew,Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78,Elective,2020-12-18,Ibuprofen,21-30
4,Adrienne,Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.32,Urgent,2022-10-09,Penicillin,41-50

In [ ]:
# Summary of numerical data
df.describe()

                Age  Billing Amount
count  55500.000000    55500.000000
mean      51.539459    25539.316071
std       19.602454    14211.454434
min       13.000000    -2008.490000
25%       35.000000    13241.222500
50%       52.000000    25538.065000
75%       68.000000    37820.510000
max       89.000000    52764.280000

In [10]:
# Distribution of categorical data 
for col in ['Gender', 'Admission Type', 'Medical Condition', 'Insurance Provider', 'Blood Type']:
    print(f"\n--- {col} ---")
    print(df[col].value_counts())

--- Gender ---
Gender
Male      27774
Female    27726
Name: count, dtype: int64

--- Admission Type ---
Admission Type
Elective     18655
Urgent       18576
Emergency    18269
Name: count, dtype: int64

--- Medical Condition ---
Medical Condition
Arthritis       9308
Diabetes        9304
Hypertension    9245
Obesity         9231
Cancer          9227
Asthma          9185
Name: count, dtype: int64

--- Insurance Provider ---
Insurance Provider
Cigna               11249
Medicare            11154
UnitedHealthcare    11125
Blue Cross          11059
Aetna               10913
Name: count, dtype: int64

--- Blood Type ---
Blood Type
A-     6969
A+     6956
AB+    6947
AB-    6945
B+     6945
B-     6944
O+     6917
O-     6877
Name: count, dtype: int64

In [13]:
# Check for any null values
df.isnull().sum()

First Name            0
Last Name             0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Admission Type        0
Discharge Date        0
Medication            0
Age Range             0
dtype: int64

In [18]:
# Length of Stay
df['Discharge Date'] = pd.to_datetime(df['Discharge Date'], format="%Y-%m-%d")

df['Date of Admission'] = pd.to_datetime(df['Date of Admission'], format="%Y-%m-%d")

df["Length of Stay"] = (df["Discharge Date"] - df["Date of Admission"]).dt.days

df["Length of Stay"].describe()

count    55500.000000
mean        15.509009
std          8.659600
min          1.000000
25%          8.000000
50%         15.000000
75%         23.000000
max         30.000000
Name: Length of Stay, dtype: float64